import type {
  Case, Client, Invoice, Employee, Hearing, Task,
  DashboardStats, TimelineEvent, CommunicationLog,
  LeaveRecord, Expense, ChartDataPoint,
  DomainMilestoneTemplate, CaseMilestone, MilestoneDefinition, Domain,
} from "@/types";

// ============ DASHBOARD ============
export const dashboardStats: DashboardStats = {
  activeCases: 147,
  revenueThisMonth: 1845000,
  hearingsToday: 8,
  pendingTasks: 34,
  activeCasesTrend: 12.5,
  revenueTrend: 8.3,
  hearingsTrend: -2,
  tasksTrend: -15.4,
};

export const casesByDomain: ChartDataPoint[] = [
  { name: "Litigation", value: 42 },
  { name: "RERA", value: 28 },
  { name: "TNCP", value: 22 },
  { name: "IMC", value: 18 },
  { name: "Revenue", value: 15 },
  { name: "IDA", value: 12 },
  { name: "Fin. Services", value: 10 },
];

export const revenueTrend: ChartDataPoint[] = [
  { name: "Sep", value: 1200000 },
  { name: "Oct", value: 1450000 },
  { name: "Nov", value: 1380000 },
  { name: "Dec", value: 1620000 },
  { name: "Jan", value: 1780000 },
  { name: "Feb", value: 1680000 },
  { name: "Mar", value: 1845000 },
];

// ============ CASES ============
export const cases: Case[] = [
  {
    id: "LIT-2026-0142",
    clientId: "CLT-001",
    clientName: "Rajesh Sharma",
    domain: "Litigation",
    caseType: "Civil Suit",
    assignedTo: "Anil Verma",
    coAssigned: "Priya Mehta",
    currentStage: "Evidence Stage",
    stageStatus: "In Progress",
    nextActionDate: "2026-03-15",
    nextHearingDate: "2026-03-18",
    feeAgreed: 250000,
    amountReceived: 150000,
    amountOutstanding: 100000,
    priority: "High",
    status: "Active",
    createdDate: "2025-08-12",
    lastUpdated: "2026-03-07",
  },
  {
    id: "RERA-2026-0089",
    clientId: "CLT-002",
    clientName: "Sunita Agarwal",
    domain: "RERA",
    caseType: "Buyer Complaint",
    assignedTo: "Rohan Gupta",
    currentStage: "Arguments",
    stageStatus: "Awaiting Response",
    nextActionDate: "2026-03-12",
    nextHearingDate: "2026-03-20",
    feeAgreed: 180000,
    amountReceived: 90000,
    amountOutstanding: 90000,
    priority: "Urgent",
    status: "Active",
    createdDate: "2025-11-05",
    lastUpdated: "2026-03-06",
  },
  {
    id: "TNCP-2026-0034",
    clientId: "CLT-003",
    clientName: "Vikram Builders Pvt. Ltd.",
    domain: "TNCP",
    caseType: "Layout Approval",
    assignedTo: "Sneha Patel",
    currentStage: "Scrutiny & Objections",
    stageStatus: "In Progress",
    nextActionDate: "2026-03-14",
    feeAgreed: 350000,
    amountReceived: 175000,
    amountOutstanding: 175000,
    priority: "Normal",
    status: "Active",
    createdDate: "2025-12-20",
    lastUpdated: "2026-03-05",
  },
  {
    id: "IMC-2026-0056",
    clientId: "CLT-004",
    clientName: "Mahesh Jain",
    domain: "IMC",
    caseType: "Building Plan Sanction",
    assignedTo: "Vikash Singh",
    currentStage: "Technical Objections",
    stageStatus: "Awaiting Response",
    nextActionDate: "2026-03-11",
    feeAgreed: 120000,
    amountReceived: 60000,
    amountOutstanding: 60000,
    priority: "High",
    status: "Active",
    createdDate: "2026-01-10",
    lastUpdated: "2026-03-04",
  },
  {
    id: "IDA-2026-0023",
    clientId: "CLT-005",
    clientName: "Neelam Enterprises",
    domain: "IDA",
    caseType: "Plot Transfer",
    assignedTo: "Meera Sharma",
    currentStage: "Scrutiny by IDA",
    stageStatus: "Pending",
    nextActionDate: "2026-03-16",
    feeAgreed: 95000,
    amountReceived: 47500,
    amountOutstanding: 47500,
    priority: "Normal",
    status: "Active",
    createdDate: "2026-02-01",
    lastUpdated: "2026-03-02",
  },
  {
    id: "REV-2026-0017",
    clientId: "CLT-006",
    clientName: "Ramesh Patidar",
    domain: "Revenue",
    caseType: "Mutation",
    assignedTo: "Deepak Rawat",
    currentStage: "Hearing / Objection",
    stageStatus: "In Progress",
    nextActionDate: "2026-03-13",
    nextHearingDate: "2026-03-13",
    feeAgreed: 75000,
    amountReceived: 75000,
    amountOutstanding: 0,
    priority: "Normal",
    status: "Active",
    createdDate: "2026-01-15",
    lastUpdated: "2026-03-06",
  },
  {
    id: "FIN-2026-0011",
    clientId: "CLT-007",
    clientName: "Anita Dubey",
    domain: "Financial Services",
    caseType: "Loan Processing",
    assignedTo: "Rahul Tiwari",
    currentStage: "Bank Processing",
    stageStatus: "In Progress",
    nextActionDate: "2026-03-10",
    feeAgreed: 50000,
    amountReceived: 25000,
    amountOutstanding: 25000,
    priority: "Normal",
    status: "Active",
    createdDate: "2026-02-10",
    lastUpdated: "2026-03-08",
  },
  {
    id: "LIT-2026-0143",
    clientId: "CLT-008",
    clientName: "Prakash Industries",
    domain: "Litigation",
    caseType: "Writ Petition",
    assignedTo: "Anil Verma",
    currentStage: "Plaint Drafting",
    stageStatus: "In Progress",
    nextActionDate: "2026-03-10",
    feeAgreed: 500000,
    amountReceived: 250000,
    amountOutstanding: 250000,
    priority: "Urgent",
    status: "Active",
    createdDate: "2026-03-01",
    lastUpdated: "2026-03-08",
  },
  {
    id: "RERA-2026-0090",
    clientId: "CLT-009",
    clientName: "Kavita Saxena",
    domain: "RERA",
    caseType: "Buyer Complaint",
    assignedTo: "Rohan Gupta",
    currentStage: "Online Filing",
    stageStatus: "Completed",
    nextActionDate: "2026-03-22",
    feeAgreed: 160000,
    amountReceived: 80000,
    amountOutstanding: 80000,
    priority: "Normal",
    status: "Active",
    createdDate: "2026-02-15",
    lastUpdated: "2026-03-07",
  },
  {
    id: "LIT-2025-0098",
    clientId: "CLT-010",
    clientName: "Deepak Malhotra",
    domain: "Litigation",
    caseType: "Criminal Case",
    assignedTo: "Anil Verma",
    currentStage: "Judgment Awaited",
    stageStatus: "Pending",
    nextActionDate: "2026-03-25",
    nextHearingDate: "2026-03-25",
    feeAgreed: 300000,
    amountReceived: 250000,
    amountOutstanding: 50000,
    priority: "High",
    status: "Active",
    createdDate: "2025-06-18",
    lastUpdated: "2026-03-03",
  },
];

export const upcomingHearings: Hearing[] = [
  {
    id: "HR-001",
    caseId: "LIT-2026-0142",
    caseTitle: "Sharma vs. State Bank — Civil Suit Recovery",
    clientName: "Rajesh Sharma",
    date: "2026-03-09",
    court: "District Court, Indore — Court No. 5",
    purpose: "Evidence — Cross-examination of DW-1",
    advocate: "Anil Verma",
  },
  {
    id: "HR-002",
    caseId: "RERA-2026-0089",
    caseTitle: "Agarwal vs. Sunrise Builders — RERA Complaint",
    clientName: "Sunita Agarwal",
    date: "2026-03-09",
    court: "MP RERA, Bhopal — Bench A",
    purpose: "Arguments",
    advocate: "Rohan Gupta",
  },
  {
    id: "HR-003",
    caseId: "REV-2026-0017",
    caseTitle: "Patidar — Mutation Namantar",
    clientName: "Ramesh Patidar",
    date: "2026-03-09",
    court: "Tehsildar Office, Indore",
    purpose: "Hearing on objections",
    advocate: "Deepak Rawat",
  },
  {
    id: "HR-004",
    caseId: "LIT-2025-0098",
    caseTitle: "State vs. Malhotra — Criminal Defense",
    clientName: "Deepak Malhotra",
    date: "2026-03-10",
    court: "Sessions Court, Indore",
    purpose: "Arguments on charge",
    advocate: "Anil Verma",
  },
  {
    id: "HR-005",
    caseId: "LIT-2026-0142",
    caseTitle: "Sharma vs. State Bank — Civil Suit Recovery",
    clientName: "Rajesh Sharma",
    date: "2026-03-18",
    court: "District Court, Indore — Court No. 5",
    purpose: "Evidence — Cross-examination of DW-2",
    advocate: "Anil Verma",
  },
];

export const overduePayments: Invoice[] = [
  {
    id: "INV-001",
    invoiceNumber: "INV-2026-0234",
    clientId: "CLT-002",
    clientName: "Sunita Agarwal",
    caseId: "RERA-2026-0089",
    amount: 90000,
    paidAmount: 0,
    gstAmount: 16200,
    status: "Overdue",
    issueDate: "2026-01-15",
    dueDate: "2026-02-15",
    description: "Professional fees — RERA complaint (2nd instalment)",
  },
  {
    id: "INV-002",
    invoiceNumber: "INV-2026-0198",
    clientId: "CLT-004",
    clientName: "Mahesh Jain",
    caseId: "IMC-2026-0056",
    amount: 60000,
    paidAmount: 0,
    gstAmount: 10800,
    status: "Overdue",
    issueDate: "2026-02-01",
    dueDate: "2026-03-01",
    description: "Professional fees — Building Plan Sanction (Balance)",
  },
  {
    id: "INV-003",
    invoiceNumber: "INV-2026-0256",
    clientId: "CLT-008",
    clientName: "Prakash Industries",
    caseId: "LIT-2026-0143",
    amount: 250000,
    paidAmount: 0,
    gstAmount: 45000,
    status: "Overdue",
    issueDate: "2026-02-15",
    dueDate: "2026-03-05",
    description: "Professional fees — Writ Petition (Filing fee instalment)",
  },
];

// ============ CLIENTS ============
export const clients: Client[] = [
  {
    id: "CLT-001",
    name: "Rajesh Sharma",
    clientType: "Individual",
    phone: "+91 98765 43210",
    email: "rajesh.sharma@email.com",
    address: "45, Vijay Nagar, Indore",
    source: "Referral",
    referredBy: "Adv. Kapoor",
    clientSince: "2024-03-15",
    relationshipManager: "Anil Verma",
    tags: ["VIP", "Litigation"],
    activeCases: 1,
    totalCases: 3,
    outstandingAmount: 100000,
    totalPaid: 450000,
  },
  {
    id: "CLT-002",
    name: "Sunita Agarwal",
    clientType: "Individual",
    phone: "+91 87654 32109",
    email: "sunita.a@email.com",
    address: "12, Palasia, Indore",
    source: "Walk-in",
    clientSince: "2025-11-05",
    relationshipManager: "Rohan Gupta",
    tags: ["RERA Client"],
    activeCases: 1,
    totalCases: 1,
    outstandingAmount: 90000,
    totalPaid: 90000,
  },
  {
    id: "CLT-003",
    name: "Vikram Builders Pvt. Ltd.",
    clientType: "Company",
    phone: "+91 76543 21098",
    email: "info@vikrambuilders.com",
    address: "Super Corridor, Indore",
    source: "Online",
    clientSince: "2025-06-10",
    relationshipManager: "Sneha Patel",
    tags: ["Builder", "TNCP", "Recurring"],
    activeCases: 2,
    totalCases: 5,
    outstandingAmount: 175000,
    totalPaid: 825000,
  },
  {
    id: "CLT-004",
    name: "Mahesh Jain",
    clientType: "Individual",
    phone: "+91 65432 10987",
    email: "mahesh.jain@email.com",
    address: "Scheme No. 78, Indore",
    source: "Referral",
    referredBy: "Rajesh Sharma",
    clientSince: "2026-01-10",
    relationshipManager: "Vikash Singh",
    tags: ["IMC"],
    activeCases: 1,
    totalCases: 1,
    outstandingAmount: 60000,
    totalPaid: 60000,
  },
  {
    id: "CLT-005",
    name: "Neelam Enterprises",
    clientType: "Partnership",
    phone: "+91 54321 09876",
    email: "neelam.ent@email.com",
    address: "MG Road, Indore",
    source: "Referral",
    clientSince: "2025-09-20",
    relationshipManager: "Meera Sharma",
    tags: ["IDA"],
    activeCases: 1,
    totalCases: 2,
    outstandingAmount: 47500,
    totalPaid: 142500,
  },
  {
    id: "CLT-006",
    name: "Ramesh Patidar",
    clientType: "Individual",
    phone: "+91 43210 98765",
    address: "Mhow, Indore",
    source: "Walk-in",
    clientSince: "2026-01-15",
    relationshipManager: "Deepak Rawat",
    tags: ["Revenue"],
    activeCases: 1,
    totalCases: 1,
    outstandingAmount: 0,
    totalPaid: 75000,
  },
  {
    id: "CLT-007",
    name: "Anita Dubey",
    clientType: "Individual",
    phone: "+91 32109 87654",
    email: "anita.dubey@email.com",
    address: "Sapna Sangeeta, Indore",
    source: "Online",
    clientSince: "2026-02-10",
    relationshipManager: "Rahul Tiwari",
    tags: ["Financial Services"],
    activeCases: 1,
    totalCases: 1,
    outstandingAmount: 25000,
    totalPaid: 25000,
  },
  {
    id: "CLT-008",
    name: "Prakash Industries",
    clientType: "Company",
    phone: "+91 21098 76543",
    email: "legal@prakashind.com",
    address: "Pithampur Industrial Area",
    source: "Referral",
    referredBy: "CA Deepak Goyal",
    clientSince: "2025-01-20",
    relationshipManager: "Rohan Gupta",
    tags: ["VIP", "Corporate", "Litigation"],
    activeCases: 2,
    totalCases: 4,
    outstandingAmount: 250000,
    totalPaid: 1200000,
  },
];

// ============ INVOICES ============
export const invoices: Invoice[] = [
  ...overduePayments,
  {
    id: "INV-004",
    invoiceNumber: "INV-2026-0267",
    clientId: "CLT-001",
    clientName: "Rajesh Sharma",
    caseId: "LIT-2026-0142",
    amount: 100000,
    paidAmount: 0,
    gstAmount: 18000,
    status: "Pending",
    issueDate: "2026-03-01",
    dueDate: "2026-03-31",
    description: "Professional fees — Civil Suit (Final instalment)",
  },
  {
    id: "INV-005",
    invoiceNumber: "INV-2026-0245",
    clientId: "CLT-003",
    clientName: "Vikram Builders Pvt. Ltd.",
    caseId: "TNCP-2026-0034",
    amount: 175000,
    paidAmount: 175000,
    gstAmount: 31500,
    status: "Paid",
    issueDate: "2026-01-20",
    dueDate: "2026-02-20",
    description: "Professional fees — Layout Approval (1st instalment)",
  },
  {
    id: "INV-006",
    invoiceNumber: "INV-2026-0250",
    clientId: "CLT-006",
    clientName: "Ramesh Patidar",
    caseId: "REV-2026-0017",
    amount: 75000,
    paidAmount: 75000,
    gstAmount: 13500,
    status: "Paid",
    issueDate: "2026-01-15",
    dueDate: "2026-02-15",
    description: "Professional fees — Mutation (Full payment)",
  },
  {
    id: "INV-007",
    invoiceNumber: "INV-2026-0260",
    clientId: "CLT-005",
    clientName: "Neelam Enterprises",
    caseId: "IDA-2026-0023",
    amount: 47500,
    paidAmount: 25000,
    gstAmount: 8550,
    status: "Partially Paid",
    issueDate: "2026-02-05",
    dueDate: "2026-03-05",
    description: "Professional fees — Plot Transfer (1st instalment)",
  },
  {
    id: "INV-008",
    invoiceNumber: "INV-2026-0270",
    clientId: "CLT-009",
    clientName: "Kavita Saxena",
    caseId: "RERA-2026-0090",
    amount: 80000,
    paidAmount: 80000,
    gstAmount: 14400,
    status: "Paid",
    issueDate: "2026-02-15",
    dueDate: "2026-03-15",
    description: "Professional fees — RERA Complaint (1st instalment)",
  },
];

// ============ EMPLOYEES ============
export const employees: Employee[] = [
  {
    id: "EMP-001",
    name: "Priya Mehta",
    designation: "Managing Partner",
    department: "Admin",
    dateOfJoining: "2018-04-01",
    phone: "+91 99887 76655",
    email: "priya@lexops.in",
    qualification: "LLB, LLM (Constitutional Law)",
    barCouncilNumber: "MP/1234/2018",
    reportingTo: "—",
    activeCases: 0,
    pendingTasks: 5,
  },
  {
    id: "EMP-002",
    name: "Rohan Gupta",
    designation: "RERA Senior Associate",
    department: "RERA",
    dateOfJoining: "2020-07-15",
    phone: "+91 88776 65544",
    email: "rohan@lexops.in",
    qualification: "LLB, Diploma in Real Estate Law",
    barCouncilNumber: "MP/2345/2020",
    reportingTo: "Priya Mehta",
    activeCases: 2,
    pendingTasks: 7,
  },
  {
    id: "EMP-003",
    name: "Sneha Patel",
    designation: "TNCP Associate",
    department: "TNCP",
    dateOfJoining: "2021-01-10",
    phone: "+91 77665 54433",
    email: "sneha@lexops.in",
    qualification: "LLB, MCom",
    barCouncilNumber: "MP/3456/2021",
    reportingTo: "Priya Mehta",
    activeCases: 1,
    pendingTasks: 4,
  },
  {
    id: "EMP-004",
    name: "Anil Verma",
    designation: "Litigation Associate",
    department: "Litigation",
    dateOfJoining: "2019-09-01",
    phone: "+91 66554 43322",
    email: "anil@lexops.in",
    qualification: "LLB, LLM (Criminal Law)",
    barCouncilNumber: "MP/4567/2019",
    reportingTo: "Priya Mehta",
    activeCases: 3,
    pendingTasks: 8,
  },
  {
    id: "EMP-005",
    name: "Rahul Tiwari",
    designation: "Financial Services Associate",
    department: "Financial Services",
    dateOfJoining: "2023-03-15",
    phone: "+91 55443 32211",
    email: "rahul@lexops.in",
    qualification: "LLB, MBA (Finance)",
    barCouncilNumber: "MP/5678/2023",
    reportingTo: "Priya Mehta",
    activeCases: 1,
    pendingTasks: 3,
  },
  {
    id: "EMP-006",
    name: "Meera Sharma",
    designation: "IDA Associate",
    department: "IDA",
    dateOfJoining: "2022-06-01",
    phone: "+91 44332 21100",
    email: "meera@lexops.in",
    qualification: "BA LLB",
    barCouncilNumber: "MP/6789/2022",
    reportingTo: "Priya Mehta",
    activeCases: 1,
    pendingTasks: 4,
  },
  {
    id: "EMP-007",
    name: "Vikash Singh",
    designation: "IMC Associate",
    department: "IMC",
    dateOfJoining: "2022-09-01",
    phone: "+91 22110 98877",
    email: "vikash@lexops.in",
    qualification: "LLB, Diploma in Municipal Law",
    barCouncilNumber: "MP/7890/2022",
    reportingTo: "Priya Mehta",
    activeCases: 1,
    pendingTasks: 3,
  },
  {
    id: "EMP-008",
    name: "Deepak Rawat",
    designation: "Revenue Associate",
    department: "Revenue",
    dateOfJoining: "2023-01-15",
    phone: "+91 11009 87766",
    email: "deepak@lexops.in",
    qualification: "LLB, LLM (Revenue Law)",
    barCouncilNumber: "MP/8901/2023",
    reportingTo: "Priya Mehta",
    activeCases: 1,
    pendingTasks: 2,
  },
  {
    id: "EMP-009",
    name: "Sanjay Kushwaha",
    designation: "Accountant",
    department: "Admin",
    dateOfJoining: "2021-08-15",
    phone: "+91 33221 10099",
    email: "sanjay@lexops.in",
    qualification: "BCom, CA Inter",
    reportingTo: "Priya Mehta",
    activeCases: 0,
    pendingTasks: 6,
  },
];

export const tasks: Task[] = [
  {
    id: "TSK-001",
    title: "Prepare cross-examination notes for DW-1",
    caseId: "LIT-2026-0142",
    assignedBy: "Priya Mehta",
    assignedTo: "Anil Verma",
    dueDate: "2026-03-09",
    priority: "Urgent",
    status: "In Progress",
  },
  {
    id: "TSK-002",
    title: "Draft RERA complaint rejoinder",
    caseId: "RERA-2026-0089",
    assignedBy: "Rohan Gupta",
    assignedTo: "Rohan Gupta",
    dueDate: "2026-03-10",
    priority: "High",
    status: "To Do",
  },
  {
    id: "TSK-003",
    title: "Collect revised drawings from architect",
    caseId: "IMC-2026-0056",
    assignedBy: "Vikash Singh",
    assignedTo: "Vikash Singh",
    dueDate: "2026-03-11",
    priority: "Normal",
    status: "To Do",
  },
  {
    id: "TSK-004",
    title: "Follow up on bank loan processing status",
    caseId: "FIN-2026-0011",
    assignedBy: "Rahul Tiwari",
    assignedTo: "Rahul Tiwari",
    dueDate: "2026-03-10",
    priority: "Normal",
    status: "In Progress",
  },
  {
    id: "TSK-005",
    title: "Generate monthly invoice batch for February",
    assignedBy: "Priya Mehta",
    assignedTo: "Sanjay Kushwaha",
    dueDate: "2026-03-10",
    priority: "High",
    status: "To Do",
  },
  {
    id: "TSK-006",
    title: "File mutation hearing report",
    caseId: "REV-2026-0017",
    assignedBy: "Priya Mehta",
    assignedTo: "Priya Mehta",
    dueDate: "2026-03-13",
    priority: "Normal",
    status: "To Do",
  },
];

export const timelineEvents: TimelineEvent[] = [
  {
    id: "TL-001",
    date: "2025-08-12",
    title: "Case Created",
    description: "Civil suit case opened for Rajesh Sharma vs. State Bank",
    type: "created",
    user: "Priya Mehta",
  },
  {
    id: "TL-002",
    date: "2025-08-15",
    title: "Documents Uploaded",
    description: "Loan agreement, bank statements, and notice copies uploaded",
    type: "document",
    user: "Meera Sharma",
  },
  {
    id: "TL-003",
    date: "2025-09-01",
    title: "Plaint Filed",
    description: "Plaint filed in District Court, Indore. Case No. CS-2025-1842",
    type: "stage",
    user: "Priya Mehta",
  },
  {
    id: "TL-004",
    date: "2025-10-15",
    title: "First Hearing",
    description: "Notice issued to defendant. Next date for written statement",
    type: "hearing",
    user: "Priya Mehta",
  },
  {
    id: "TL-005",
    date: "2025-12-10",
    title: "Payment Received",
    description: "₹75,000 received via bank transfer (2nd instalment)",
    type: "payment",
    user: "Sanjay Kushwaha",
  },
  {
    id: "TL-006",
    date: "2026-01-20",
    title: "Evidence Stage Began",
    description: "Case moved to evidence stage. Affidavit of evidence filed",
    type: "stage",
    user: "Priya Mehta",
  },
  {
    id: "TL-007",
    date: "2026-03-07",
    title: "Client Communication",
    description: "WhatsApp update sent to client regarding hearing preparation",
    type: "communication",
    user: "Priya Mehta",
  },
];

export const communicationLogs: CommunicationLog[] = [
  {
    id: "COM-001",
    type: "WhatsApp",
    date: "2026-03-07",
    summary: "Updated client about upcoming hearing on March 18. Advised to keep documents ready.",
    followUpRequired: false,
  },
  {
    id: "COM-002",
    type: "Call",
    date: "2026-03-05",
    summary: "Discussed evidence preparation. Client confirmed availability for next hearing.",
    followUpRequired: true,
    followUpDate: "2026-03-15",
  },
  {
    id: "COM-003",
    type: "In-Person",
    date: "2026-02-20",
    summary: "Office meeting to review case progress and discuss settlement possibility.",
    followUpRequired: false,
  },
  {
    id: "COM-004",
    type: "Email",
    date: "2026-02-10",
    summary: "Sent copy of affidavit of evidence for review and approval.",
    followUpRequired: true,
    followUpDate: "2026-02-15",
  },
];

export const leaveRecords: LeaveRecord[] = [
  {
    id: "LV-001",
    employeeId: "EMP-002",
    type: "Casual",
    startDate: "2026-03-15",
    endDate: "2026-03-16",
    status: "Approved",
    reason: "Personal work",
  },
  {
    id: "LV-002",
    employeeId: "EMP-006",
    type: "Sick",
    startDate: "2026-03-05",
    endDate: "2026-03-06",
    status: "Approved",
    reason: "Unwell",
  },
  {
    id: "LV-003",
    employeeId: "EMP-003",
    type: "Earned",
    startDate: "2026-03-20",
    endDate: "2026-03-25",
    status: "Pending",
    reason: "Family function",
  },
];

export const expenses: Expense[] = [
  {
    id: "EXP-001",
    date: "2026-03-05",
    amount: 5000,
    category: "Court Fee",
    description: "Court fee for filing evidence affidavit",
    paidBy: "Firm",
    caseId: "LIT-2026-0142",
    type: "Client Disbursement",
  },
  {
    id: "EXP-002",
    date: "2026-03-03",
    amount: 15000,
    category: "Rent",
    description: "Office rent — March 2026",
    paidBy: "Firm",
    type: "Office Expense",
  },
  {
    id: "EXP-003",
    date: "2026-03-02",
    amount: 2500,
    category: "Filing Fee",
    description: "RERA complaint filing fee",
    paidBy: "Firm",
    caseId: "RERA-2026-0090",
    type: "Client Disbursement",
  },
  {
    id: "EXP-004",
    date: "2026-03-01",
    amount: 3000,
    category: "Stationery",
    description: "Printer paper, cartridges, and files",
    paidBy: "Meera Sharma",
    type: "Office Expense",
  },
  {
    id: "EXP-005",
    date: "2026-03-07",
    amount: 8500,
    category: "Travel",
    description: "Bhopal trip — RERA hearing",
    paidBy: "Rohan Gupta",
    caseId: "RERA-2026-0089",
    type: "Client Disbursement",
  },
];

// ============ MILESTONE TEMPLATES (per domain) ============

export const domainMilestoneTemplates: DomainMilestoneTemplate[] = [
  {
    domain: "Litigation",
    milestones: [
      { id: "LIT-M01", name: "Client Consultation & Case Assessment", description: "Initial meeting, understanding facts, assessing merits & risk", order: 1, estimatedDays: 3 },
      { id: "LIT-M02", name: "Case Registration & Documentation", description: "Collect documents, file index, vakalatnama, court fees", order: 2, estimatedDays: 5 },
      { id: "LIT-M03", name: "Plaint / Petition Drafting", description: "Draft plaint, petition, or application with supporting affidavit", order: 3, estimatedDays: 7 },
      { id: "LIT-M04", name: "Filing in Court", description: "File case in appropriate court, obtain case number", order: 4, estimatedDays: 3 },
      { id: "LIT-M05", name: "Notice / Summons Service", description: "Ensure service of notice/summons on opposite party", order: 5, estimatedDays: 14 },
      { id: "LIT-M06", name: "Written Statement / Reply", description: "Receive or file written statement, reply, or rejoinder", order: 6, estimatedDays: 21 },
      { id: "LIT-M07", name: "Framing of Issues", description: "Court frames issues for trial based on pleadings", order: 7, estimatedDays: 7 },
      { id: "LIT-M08", name: "Evidence Stage", description: "File affidavit of evidence, cross-examination of witnesses", order: 8, estimatedDays: 60 },
      { id: "LIT-M09", name: "Arguments", description: "Final arguments by both parties before the court", order: 9, estimatedDays: 14 },
      { id: "LIT-M10", name: "Judgment / Order", description: "Court pronounces judgment or passes order", order: 10, estimatedDays: 30 },
      { id: "LIT-M11", name: "Execution / Compliance", description: "Execute decree, ensure compliance with court order", order: 11, estimatedDays: 30 },
      { id: "LIT-M12", name: "Case Closure", description: "Final billing, archive documents, close file", order: 12, estimatedDays: 5 },
    ],
  },
  {
    domain: "RERA",
    milestones: [
      { id: "RERA-M01", name: "Client Consultation", description: "Review allotment letter, builder agreement, payment receipts", order: 1, estimatedDays: 3 },
      { id: "RERA-M02", name: "Document Collection & Review", description: "Gather all correspondence, builder notices, possession letters", order: 2, estimatedDays: 5 },
      { id: "RERA-M03", name: "Legal Notice to Builder", description: "Draft and send legal notice demanding compliance/refund", order: 3, estimatedDays: 7 },
      { id: "RERA-M04", name: "Online RERA Complaint Filing", description: "File complaint on RERA portal with supporting documents", order: 4, estimatedDays: 5 },
      { id: "RERA-M05", name: "Hearing Notice Received", description: "Receive hearing date from RERA authority", order: 5, estimatedDays: 14 },
      { id: "RERA-M06", name: "Evidence & Document Submission", description: "Submit affidavit, documentary evidence to RERA bench", order: 6, estimatedDays: 14 },
      { id: "RERA-M07", name: "Arguments", description: "Present oral arguments before RERA authority", order: 7, estimatedDays: 7 },
      { id: "RERA-M08", name: "Interim Order", description: "Apply for or receive interim relief order if applicable", order: 8, estimatedDays: 14 },
      { id: "RERA-M09", name: "Final Order", description: "RERA authority passes final order/direction", order: 9, estimatedDays: 30 },
      { id: "RERA-M10", name: "Execution / Compliance", description: "Ensure builder complies with order, follow up on refund/possession", order: 10, estimatedDays: 30 },
      { id: "RERA-M11", name: "Case Closure", description: "Final billing, archive documents, close file", order: 11, estimatedDays: 5 },
    ],
  },
  {
    domain: "TNCP",
    milestones: [
      { id: "TNCP-M01", name: "Client Consultation", description: "Understand land details, intended use, existing permissions", order: 1, estimatedDays: 3 },
      { id: "TNCP-M02", name: "Document Collection & Survey", description: "Collect khasra, map, survey number, ownership documents", order: 2, estimatedDays: 7 },
      { id: "TNCP-M03", name: "Application Preparation", description: "Prepare layout/diversion/permission application with drawings", order: 3, estimatedDays: 10 },
      { id: "TNCP-M04", name: "Application Submission to TNCP", description: "Submit application with required fees and documents", order: 4, estimatedDays: 3 },
      { id: "TNCP-M05", name: "Scrutiny & Objections", description: "TNCP scrutinises application, raises queries/objections", order: 5, estimatedDays: 21 },
      { id: "TNCP-M06", name: "Compliance of Objections", description: "Address queries, submit revised documents/drawings", order: 6, estimatedDays: 14 },
      { id: "TNCP-M07", name: "Site Inspection", description: "TNCP team conducts site visit and inspection", order: 7, estimatedDays: 14 },
      { id: "TNCP-M08", name: "Technical Committee Review", description: "Technical committee reviews and recommends approval/rejection", order: 8, estimatedDays: 21 },
      { id: "TNCP-M09", name: "Approval / Rejection Order", description: "TNCP issues final approval or rejection order", order: 9, estimatedDays: 14 },
      { id: "TNCP-M10", name: "Case Closure", description: "Final billing, deliver approval documents, close file", order: 10, estimatedDays: 5 },
    ],
  },
  {
    domain: "IMC",
    milestones: [
      { id: "IMC-M01", name: "Client Consultation", description: "Review property details, building requirements, zoning rules", order: 1, estimatedDays: 3 },
      { id: "IMC-M02", name: "Document Collection", description: "Collect property documents, NOCs, architect drawings", order: 2, estimatedDays: 7 },
      { id: "IMC-M03", name: "Building Plan Preparation", description: "Coordinate with architect for sanctioned plan drawings", order: 3, estimatedDays: 14 },
      { id: "IMC-M04", name: "Application Submission to IMC", description: "Submit building plan application with fees", order: 4, estimatedDays: 3 },
      { id: "IMC-M05", name: "Scrutiny & Technical Objections", description: "IMC scrutinises plan, raises technical objections", order: 5, estimatedDays: 21 },
      { id: "IMC-M06", name: "Compliance of Objections", description: "Address technical objections with revised plans", order: 6, estimatedDays: 14 },
      { id: "IMC-M07", name: "Site Inspection", description: "IMC team visits site for verification", order: 7, estimatedDays: 14 },
      { id: "IMC-M08", name: "Approval / Rejection Order", description: "IMC sanctions or rejects building plan", order: 8, estimatedDays: 14 },
      { id: "IMC-M09", name: "Construction NOC", description: "Obtain No Objection Certificate for construction", order: 9, estimatedDays: 7 },
      { id: "IMC-M10", name: "Case Closure", description: "Final billing, deliver sanctioned plan, close file", order: 10, estimatedDays: 5 },
    ],
  },
  {
    domain: "IDA",
    milestones: [
      { id: "IDA-M01", name: "Client Consultation", description: "Understand property/plot details, purpose of application", order: 1, estimatedDays: 3 },
      { id: "IDA-M02", name: "Document Verification", description: "Verify allotment letter, lease deed, payment receipts", order: 2, estimatedDays: 5 },
      { id: "IDA-M03", name: "Application Submission to IDA", description: "Submit transfer/mutation/permission application", order: 3, estimatedDays: 3 },
      { id: "IDA-M04", name: "Scrutiny by IDA", description: "IDA reviews application and supporting documents", order: 4, estimatedDays: 21 },
      { id: "IDA-M05", name: "Compliance of Queries", description: "Respond to IDA queries with additional documents", order: 5, estimatedDays: 14 },
      { id: "IDA-M06", name: "NOC from Other Departments", description: "Obtain required NOCs from revenue, TNCP, etc.", order: 6, estimatedDays: 21 },
      { id: "IDA-M07", name: "Site Verification", description: "IDA conducts physical verification of property", order: 7, estimatedDays: 14 },
      { id: "IDA-M08", name: "Approval / Allotment Order", description: "IDA issues approval, transfer, or allotment order", order: 8, estimatedDays: 14 },
      { id: "IDA-M09", name: "Registration / Transfer", description: "Complete registration or transfer at sub-registrar office", order: 9, estimatedDays: 14 },
      { id: "IDA-M10", name: "Case Closure", description: "Final billing, deliver documents, close file", order: 10, estimatedDays: 5 },
    ],
  },
  {
    domain: "Revenue",
    milestones: [
      { id: "REV-M01", name: "Client Consultation", description: "Understand land/property issue, mutation/demarcation need", order: 1, estimatedDays: 3 },
      { id: "REV-M02", name: "Document Collection", description: "Collect khasra, B1, map, rin pustika, succession documents", order: 2, estimatedDays: 7 },
      { id: "REV-M03", name: "Application Filing", description: "File mutation/demarcation/correction application at tehsil", order: 3, estimatedDays: 3 },
      { id: "REV-M04", name: "Notice to Concerned Parties", description: "Ensure notice served to all concerned parties", order: 4, estimatedDays: 14 },
      { id: "REV-M05", name: "Hearing / Objection Stage", description: "Attend hearings, handle objections from parties", order: 5, estimatedDays: 30 },
      { id: "REV-M06", name: "Evidence & Document Submission", description: "Submit supporting documents and evidence at hearing", order: 6, estimatedDays: 14 },
      { id: "REV-M07", name: "Revenue Officer Order", description: "Revenue officer passes order on application", order: 7, estimatedDays: 14 },
      { id: "REV-M08", name: "Appeal (if needed)", description: "File appeal if order is unfavourable, or defend against appeal", order: 8, estimatedDays: 30 },
      { id: "REV-M09", name: "Final Order / Mutation Entry", description: "Final order passed, mutation entry updated in records", order: 9, estimatedDays: 14 },
      { id: "REV-M10", name: "Case Closure", description: "Final billing, deliver certified copies, close file", order: 10, estimatedDays: 5 },
    ],
  },
  {
    domain: "Financial Services",
    milestones: [
      { id: "FIN-M01", name: "Client Consultation", description: "Understand loan/financial requirement, eligibility assessment", order: 1, estimatedDays: 3 },
      { id: "FIN-M02", name: "Document Collection & KYC", description: "Collect income proof, KYC, property documents, ITR", order: 2, estimatedDays: 7 },
      { id: "FIN-M03", name: "Loan Application Preparation", description: "Prepare loan application with all supporting documents", order: 3, estimatedDays: 5 },
      { id: "FIN-M04", name: "Application Submission to Bank/NBFC", description: "Submit loan application to chosen bank or financial institution", order: 4, estimatedDays: 3 },
      { id: "FIN-M05", name: "Bank Processing & Verification", description: "Bank verifies documents, CIBIL check, field investigation", order: 5, estimatedDays: 14 },
      { id: "FIN-M06", name: "Valuation & Legal Opinion", description: "Property valuation and legal opinion by bank's panel", order: 6, estimatedDays: 14 },
      { id: "FIN-M07", name: "Sanction / Rejection", description: "Bank issues sanction letter or rejection with reasons", order: 7, estimatedDays: 7 },
      { id: "FIN-M08", name: "Disbursement", description: "Loan amount disbursed after agreement execution", order: 8, estimatedDays: 7 },
      { id: "FIN-M09", name: "Post-Disbursement Follow-up", description: "Ensure EMI setup, insurance, and compliance", order: 9, estimatedDays: 14 },
      { id: "FIN-M10", name: "Case Closure", description: "Final billing, deliver documents, close file", order: 10, estimatedDays: 5 },
    ],
  },
];

// Helper: get milestone template for a domain
export function getMilestoneTemplate(domain: Domain): MilestoneDefinition[] {
  return domainMilestoneTemplates.find((t) => t.domain === domain)?.milestones ?? [];
}

// ============ MOCK CASE MILESTONES (pre-populated for existing cases) ============

export const caseMilestones: CaseMilestone[] = [
  // LIT-2026-0142 — Litigation case at Evidence Stage (milestone 8)
  { id: "CM-001", caseId: "LIT-2026-0142", name: "Client Consultation & Case Assessment", description: "Initial meeting, understanding facts, assessing merits & risk", order: 1, status: "Completed", assignedTo: "Anil Verma", startDate: "2025-08-12", completedDate: "2025-08-14" },
  { id: "CM-002", caseId: "LIT-2026-0142", name: "Case Registration & Documentation", description: "Collect documents, file index, vakalatnama, court fees", order: 2, status: "Completed", assignedTo: "Anil Verma", startDate: "2025-08-14", completedDate: "2025-08-18" },
  { id: "CM-003", caseId: "LIT-2026-0142", name: "Plaint / Petition Drafting", description: "Draft plaint with supporting affidavit", order: 3, status: "Completed", assignedTo: "Anil Verma", startDate: "2025-08-18", completedDate: "2025-08-28" },
  { id: "CM-004", caseId: "LIT-2026-0142", name: "Filing in Court", description: "Filed in District Court, Indore. Case No. CS-2025-1842", order: 4, status: "Completed", assignedTo: "Anil Verma", startDate: "2025-08-29", completedDate: "2025-09-01" },
  { id: "CM-005", caseId: "LIT-2026-0142", name: "Notice / Summons Service", description: "Notice issued to defendant", order: 5, status: "Completed", assignedTo: "Anil Verma", startDate: "2025-09-02", completedDate: "2025-09-20" },
  { id: "CM-006", caseId: "LIT-2026-0142", name: "Written Statement / Reply", description: "Received written statement from defendant", order: 6, status: "Completed", assignedTo: "Anil Verma", startDate: "2025-10-15", completedDate: "2025-11-10" },
  { id: "CM-007", caseId: "LIT-2026-0142", name: "Framing of Issues", description: "Court framed 5 issues for trial", order: 7, status: "Completed", assignedTo: "Anil Verma", startDate: "2025-12-01", completedDate: "2025-12-15" },
  { id: "CM-008", caseId: "LIT-2026-0142", name: "Evidence Stage", description: "Cross-examination of DW-1 in progress", order: 8, status: "In Progress", assignedTo: "Anil Verma", startDate: "2026-01-20", dueDate: "2026-04-15" },
  { id: "CM-009", caseId: "LIT-2026-0142", name: "Arguments", description: "Final arguments pending", order: 9, status: "Not Started", assignedTo: "Anil Verma" },
  { id: "CM-010", caseId: "LIT-2026-0142", name: "Judgment / Order", description: "Awaiting judgment", order: 10, status: "Not Started", assignedTo: "Anil Verma" },
  { id: "CM-011", caseId: "LIT-2026-0142", name: "Execution / Compliance", description: "Execute decree if favourable", order: 11, status: "Not Started", assignedTo: "Anil Verma" },
  { id: "CM-012", caseId: "LIT-2026-0142", name: "Case Closure", description: "Final billing and archive", order: 12, status: "Not Started", assignedTo: "Anil Verma" },

  // RERA-2026-0089 — RERA case at Arguments (milestone 7)
  { id: "CM-013", caseId: "RERA-2026-0089", name: "Client Consultation", description: "Reviewed allotment and payment details", order: 1, status: "Completed", assignedTo: "Rohan Gupta", startDate: "2025-11-05", completedDate: "2025-11-07" },
  { id: "CM-014", caseId: "RERA-2026-0089", name: "Document Collection & Review", description: "Gathered builder correspondence and receipts", order: 2, status: "Completed", assignedTo: "Rohan Gupta", startDate: "2025-11-08", completedDate: "2025-11-15" },
  { id: "CM-015", caseId: "RERA-2026-0089", name: "Legal Notice to Builder", description: "Sent legal notice demanding possession/refund", order: 3, status: "Completed", assignedTo: "Rohan Gupta", startDate: "2025-11-16", completedDate: "2025-11-25" },
  { id: "CM-016", caseId: "RERA-2026-0089", name: "Online RERA Complaint Filing", description: "Filed complaint on MP RERA portal", order: 4, status: "Completed", assignedTo: "Rohan Gupta", startDate: "2025-12-01", completedDate: "2025-12-05" },
  { id: "CM-017", caseId: "RERA-2026-0089", name: "Hearing Notice Received", description: "Hearing date assigned by RERA bench", order: 5, status: "Completed", assignedTo: "Rohan Gupta", startDate: "2025-12-20", completedDate: "2026-01-10" },
  { id: "CM-018", caseId: "RERA-2026-0089", name: "Evidence & Document Submission", description: "Submitted affidavit and documentary evidence", order: 6, status: "Completed", assignedTo: "Rohan Gupta", startDate: "2026-01-15", completedDate: "2026-02-10" },
  { id: "CM-019", caseId: "RERA-2026-0089", name: "Arguments", description: "Presenting arguments before RERA bench", order: 7, status: "In Progress", assignedTo: "Rohan Gupta", startDate: "2026-03-01", dueDate: "2026-03-20" },
  { id: "CM-020", caseId: "RERA-2026-0089", name: "Interim Order", description: "Apply for interim relief if needed", order: 8, status: "Not Started", assignedTo: "Rohan Gupta" },
  { id: "CM-021", caseId: "RERA-2026-0089", name: "Final Order", description: "Awaiting RERA final direction", order: 9, status: "Not Started", assignedTo: "Rohan Gupta" },
  { id: "CM-022", caseId: "RERA-2026-0089", name: "Execution / Compliance", description: "Ensure builder complies with order", order: 10, status: "Not Started", assignedTo: "Rohan Gupta" },
  { id: "CM-023", caseId: "RERA-2026-0089", name: "Case Closure", description: "Final billing and archive", order: 11, status: "Not Started", assignedTo: "Rohan Gupta" },

  // TNCP-2026-0034 — TNCP case at Scrutiny (milestone 5)
  { id: "CM-024", caseId: "TNCP-2026-0034", name: "Client Consultation", description: "Reviewed land details and layout plan requirements", order: 1, status: "Completed", assignedTo: "Sneha Patel", startDate: "2025-12-20", completedDate: "2025-12-22" },
  { id: "CM-025", caseId: "TNCP-2026-0034", name: "Document Collection & Survey", description: "Collected khasra, map, ownership documents", order: 2, status: "Completed", assignedTo: "Sneha Patel", startDate: "2025-12-23", completedDate: "2026-01-05" },
  { id: "CM-026", caseId: "TNCP-2026-0034", name: "Application Preparation", description: "Prepared layout approval application with drawings", order: 3, status: "Completed", assignedTo: "Sneha Patel", startDate: "2026-01-06", completedDate: "2026-01-20" },
  { id: "CM-027", caseId: "TNCP-2026-0034", name: "Application Submission to TNCP", description: "Submitted application with fees", order: 4, status: "Completed", assignedTo: "Sneha Patel", startDate: "2026-01-21", completedDate: "2026-01-24" },
  { id: "CM-028", caseId: "TNCP-2026-0034", name: "Scrutiny & Objections", description: "TNCP raised 3 objections on layout plan", order: 5, status: "In Progress", assignedTo: "Sneha Patel", startDate: "2026-02-10", dueDate: "2026-03-20" },
  { id: "CM-029", caseId: "TNCP-2026-0034", name: "Compliance of Objections", description: "Address TNCP queries", order: 6, status: "Not Started", assignedTo: "Sneha Patel" },
  { id: "CM-030", caseId: "TNCP-2026-0034", name: "Site Inspection", description: "TNCP site visit pending", order: 7, status: "Not Started", assignedTo: "Sneha Patel" },
  { id: "CM-031", caseId: "TNCP-2026-0034", name: "Technical Committee Review", description: "Technical committee review pending", order: 8, status: "Not Started", assignedTo: "Sneha Patel" },
  { id: "CM-032", caseId: "TNCP-2026-0034", name: "Approval / Rejection Order", description: "Awaiting final order", order: 9, status: "Not Started", assignedTo: "Sneha Patel" },
  { id: "CM-033", caseId: "TNCP-2026-0034", name: "Case Closure", description: "Final billing and archive", order: 10, status: "Not Started", assignedTo: "Sneha Patel" },

  // IMC-2026-0056 — IMC case at Technical Objections (milestone 5)
  { id: "CM-034", caseId: "IMC-2026-0056", name: "Client Consultation", description: "Reviewed property and building requirements", order: 1, status: "Completed", assignedTo: "Vikash Singh", startDate: "2026-01-10", completedDate: "2026-01-12" },
  { id: "CM-035", caseId: "IMC-2026-0056", name: "Document Collection", description: "Collected property documents and NOCs", order: 2, status: "Completed", assignedTo: "Vikash Singh", startDate: "2026-01-13", completedDate: "2026-01-20" },
  { id: "CM-036", caseId: "IMC-2026-0056", name: "Building Plan Preparation", description: "Architect prepared building plan drawings", order: 3, status: "Completed", assignedTo: "Vikash Singh", startDate: "2026-01-21", completedDate: "2026-02-05" },
  { id: "CM-037", caseId: "IMC-2026-0056", name: "Application Submission to IMC", description: "Submitted plan application with fees", order: 4, status: "Completed", assignedTo: "Vikash Singh", startDate: "2026-02-06", completedDate: "2026-02-08" },
  { id: "CM-038", caseId: "IMC-2026-0056", name: "Scrutiny & Technical Objections", description: "IMC raised 2 technical objections on setback", order: 5, status: "In Progress", assignedTo: "Vikash Singh", startDate: "2026-02-20", dueDate: "2026-03-15", notes: "Waiting for revised drawings from architect" },
  { id: "CM-039", caseId: "IMC-2026-0056", name: "Compliance of Objections", description: "Address technical objections", order: 6, status: "Not Started", assignedTo: "Vikash Singh" },
  { id: "CM-040", caseId: "IMC-2026-0056", name: "Site Inspection", description: "IMC site visit pending", order: 7, status: "Not Started", assignedTo: "Vikash Singh" },
  { id: "CM-041", caseId: "IMC-2026-0056", name: "Approval / Rejection Order", description: "Awaiting sanction", order: 8, status: "Not Started", assignedTo: "Vikash Singh" },
  { id: "CM-042", caseId: "IMC-2026-0056", name: "Construction NOC", description: "Obtain NOC after approval", order: 9, status: "Not Started", assignedTo: "Vikash Singh" },
  { id: "CM-043", caseId: "IMC-2026-0056", name: "Case Closure", description: "Final billing and archive", order: 10, status: "Not Started", assignedTo: "Vikash Singh" },

  // FIN-2026-0011 — Financial Services at Bank Processing (milestone 5)
  { id: "CM-044", caseId: "FIN-2026-0011", name: "Client Consultation", description: "Assessed loan requirement and eligibility", order: 1, status: "Completed", assignedTo: "Rahul Tiwari", startDate: "2026-02-10", completedDate: "2026-02-12" },
  { id: "CM-045", caseId: "FIN-2026-0011", name: "Document Collection & KYC", description: "Collected income proof, KYC, property docs", order: 2, status: "Completed", assignedTo: "Rahul Tiwari", startDate: "2026-02-13", completedDate: "2026-02-20" },
  { id: "CM-046", caseId: "FIN-2026-0011", name: "Loan Application Preparation", description: "Prepared loan application with supporting docs", order: 3, status: "Completed", assignedTo: "Rahul Tiwari", startDate: "2026-02-21", completedDate: "2026-02-25" },
  { id: "CM-047", caseId: "FIN-2026-0011", name: "Application Submission to Bank/NBFC", description: "Submitted to HDFC Bank", order: 4, status: "Completed", assignedTo: "Rahul Tiwari", startDate: "2026-02-26", completedDate: "2026-02-28" },
  { id: "CM-048", caseId: "FIN-2026-0011", name: "Bank Processing & Verification", description: "Bank verifying documents and CIBIL", order: 5, status: "In Progress", assignedTo: "Rahul Tiwari", startDate: "2026-03-01", dueDate: "2026-03-15" },
  { id: "CM-049", caseId: "FIN-2026-0011", name: "Valuation & Legal Opinion", description: "Property valuation pending", order: 6, status: "Not Started", assignedTo: "Rahul Tiwari" },
  { id: "CM-050", caseId: "FIN-2026-0011", name: "Sanction / Rejection", description: "Awaiting bank decision", order: 7, status: "Not Started", assignedTo: "Rahul Tiwari" },
  { id: "CM-051", caseId: "FIN-2026-0011", name: "Disbursement", description: "Loan disbursement pending", order: 8, status: "Not Started", assignedTo: "Rahul Tiwari" },
  { id: "CM-052", caseId: "FIN-2026-0011", name: "Post-Disbursement Follow-up", description: "EMI setup and insurance", order: 9, status: "Not Started", assignedTo: "Rahul Tiwari" },
  { id: "CM-053", caseId: "FIN-2026-0011", name: "Case Closure", description: "Final billing and archive", order: 10, status: "Not Started", assignedTo: "Rahul Tiwari" },
];
